name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip install --upgrade pip
          pip install poetry
          poetry install --no-root      

    - name: Run flake8 to improve the Quality of Code
      run: |
        poetry run flake8

    - name: Run tests and generate coverage report
      run: |
        poetry run pytest --cov=. --rootdir=tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
