name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  safety:
      runs-on: ubuntu-latest
      steps:
        - name: Safety Check
          uses: pyupio/safety@2.3.4
          with:
            api-key: ${{secrets.SAFETY_API_KEY}}
            scan: true
            file: requirements/requirements.txt

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip install --upgrade pip
          pip install poetry
          poetry install        
   
    - name: Run tests and generate coverage report
      run: |
        poetry run pytest --cov=. --rootdir=tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
